name: mynouts
description: "App de notas simple e intuitiva para organizar tus ideas y tareas diarias."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Navegación
  go_router: ^14.0.0

  # Estado global
  flutter_riverpod: ^2.5.1
  
  # Base de datos local
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3

  # Exp e imp de notas
  file_picker: ^10.3.8
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Generadores de código para Drift
  drift_dev: ^2.16.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true